[build]
    main = "frontend/"
    command = "yarn deploy"
    publish = "dist"

[[plugins]]
    package = "netlify-plugin-cache-nextjs"

[[plugins]]
    package = "netlify-plugin-cloudinary"

# Disable the broken plugins
[[plugins]]
    package = "netlify-plugin-visual-diff"
    [plugins.inputs]
        enabled = false

[[plugins]]
    package = "netlify-plugin-inline-critical-css"
    [plugins.inputs]
        enabled = false
